server:
  # 服务端口号
  port: 8767
spring:
  application:
    # 服务名，即serviceId
    name: server_consumer
eureka:
  client:
    serviceUrl:
      # 安全认证的服务注册中心地址
      defaultZone: http://admin:admin@localhost:1111/eureka/

feign:
  hystrix:
    enable: true


#server-provider:
#  ribbon:
#    MaxAutoRetries: 1
#    MaxAutoRetriesNextServer: 2
#    ConnectTimeout: 5000
#    ReadTimeout: 2000
#    OkToRetryOnAllOperations: true

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 2001